CREATE TABLE silver.data(
station_code VARCHAR(10),
date DATE,
pm25_avg FLOAT,
pm25_max FLOAT,
pm10_avg FLOAT,
pm10_max FLOAT,
no_avg FLOAT,
no_max FLOAT,
no2_avg FLOAT,
no2_max FLOAT,
so2_avg FLOAT,
so2_max FLOAT,
co_avg FLOAT,
co_max FLOAT,
nox_avg FLOAT,
nox_max FLOAT,
ozone_avg FLOAT,
ozone_max FLOAT,
at_avg FLOAT,
at_max FLOAT,
rh_avg FLOAT,
rh_max FLOAT,
ws_avg FLOAT,
ws_max FLOAT,
vws_avg FLOAT,
vws_max FLOAT,
wd_avg FLOAT,
wd_max FLOAT,
bp_avg FLOAT,
bp_max FLOAT,
nh3_avg FLOAT,
nh3_max FLOAT,
benzene_avg FLOAT,
benzene_max FLOAT,
eth_benzene_avg FLOAT,
eth_benzene_max FLOAT,
toluene_avg FLOAT,
toluene_max FLOAT,
mp_xylene_avg FLOAT,
mp_xylene_max FLOAT,
xylene_avg FLOAT,
xylene_max FLOAT
);

CREATE TABLE silver.stations(
	id INT,
	station_code NVARCHAR(50),
	city NAVARCHAR(50),
	state_code NVARCHAR(50),
	pin_code INT,
	latitude FLOAT,
	longitude FLOAT,
	elevation_m INT,
	topo_complexity FLOAT,
	coastal_proximity FLOAT,
	valley_factor FLOAT
);
