IF OBJECT_ID('gold.data','U') IS NOT NULL
  DROP TABLE gold.data

CREATE TABLE gold.data(
station_code VARCHAR(10),
date DATE,
aqi INT,
pm25_avg FLOAT,
pm25_max FLOAT,
pm10_avg FLOAT,
pm10_max FLOAT,
no_avg FLOAT,
no_max FLOAT,
no2_avg FLOAT,
no2_max FLOAT,
so2_avg FLOAT,
so2_max FLOAT,
co_avg FLOAT,
co_max FLOAT,
nox_avg FLOAT,
nox_max FLOAT,
ozone_avg FLOAT,
ozone_max FLOAT,
nh3_avg FLOAT,
nh3_max FLOAT,
benzene_avg FLOAT,
benzene_max FLOAT,
eth_benzene_avg FLOAT,
eth_benzene_max FLOAT,
toluene_avg FLOAT,
toluene_max FLOAT,
mp_xylene_avg FLOAT,
mp_xylene_max FLOAT,
xylene_avg FLOAT,
xylene_max FLOAT,
atmospheric_temperature_avg FLOAT,
atmospheric_temperature_max FLOAT,
relative_humidity_avg FLOAT,
relative_humidity_max FLOAT,
wind_speed_avg FLOAT,
wind_speed_max FLOAT,
vertical_wind_shear_avg FLOAT,
vertical_wind_shear_max FLOAT,
wind_direction_avg FLOAT,
wind_direction_max FLOAT,
barometric_pressure_avg FLOAT,
barometric_pressure_max FLOAT
)


CREATE TABLE gold.stations(
station_code VARCHAR(10),
city VARCHAR(50),
state_code VARCHAR(3),
state VARCHAR(50),
pin_code INT,
latitude FLOAT,
longitude FLOAT,
elevation_m FLOAT,
topo_complexity FLOAT,
coastal_proximity FLOAT,
valley_factor FLOAT
)
